// 쿠팡 Wing Open API 타입 정의

/** 주문 상태 */
export type CoupangOrderStatus =
  | "ACCEPT"          // 결제완료
  | "INSTRUCT"        // 상품준비중
  | "DEPARTURE"       // 배송지시
  | "DELIVERING"      // 배송중
  | "FINAL_DELIVERY"  // 배송완료
  | "NONE_TRACKING";  // 배송완료(미배송추적)

/** 주문 한 건 */
export interface CoupangOrder {
  orderId: number;
  orderTime: string;
  status: CoupangOrderStatus;
  shippingPrice: number;
  remotePrice: number;
  splitShipping: boolean;
  ableCancelTime: string;
  orderer: {
    name: string;
    email: string;
    safeNumber: string;
  };
  receiver: {
    name: string;
    safeNumber: string;
    addr1: string;
    addr2: string;
    postCode: string;
    memo: string;
  };
  orderItems: CoupangOrderItem[];
}

/** 주문 아이템 한 건 */
export interface CoupangOrderItem {
  orderItemId: number;
  vendorItemId: number;
  vendorItemName: string;
  shippingCount: number;
  unitPrice: number;
  sellerProductId: number;
  sellerProductName: string;
  sellerProductItemName: string;
  externalVendorSkuCode: string;
  invoiceNumber?: string;
  deliveryCompanyCode?: string;
}

/** 주문 목록 API 응답 */
export interface CoupangOrdersResponse {
  code: string;
  message: string;
  data: CoupangOrder[];
  nextToken?: string;
}

// ─────────────────────────────────────────────────────────────
// 상품 목록 페이징 조회 (seller_api 라우트, 마켓플레이스·로켓그로스 공용)
// GET /v2/providers/seller_api/apis/api/v1/marketplace/seller-products
// 응답은 요약 정보만 — 가격은 단건 조회에서 확인
// ─────────────────────────────────────────────────────────────

/** 상품 목록 페이징 조회 — 상품 요약 한 건 */
export interface CoupangSellerProductSummary {
  sellerProductId: number;
  sellerProductName: string;
  displayCategoryCode: number;
  categoryId: number;
  productId: number;
  vendorId: string;
  saleStartedAt: string;
  saleEndedAt: string;
  brand: string;
  statusName: string; // 심사중/임시저장/승인대기중/승인완료/부분승인완료/승인반려/상품삭제
  createdAt: string;
}

/** 상품 목록 페이징 조회 응답 */
export interface CoupangSellerProductsResponse {
  code: string;
  message: string;
  nextToken: string; // 다음 페이지 없으면 빈 문자열
  data: CoupangSellerProductSummary[];
}

// ─────────────────────────────────────────────────────────────
// 상품 단건 조회 — 이중 스키마
// GET /v2/providers/seller_api/apis/api/v1/marketplace/seller-products/{sellerProductId}
// 판매자배송 전용 상품 → 기존 스키마 (item에 salePrice 평면 존재)
// 로켓그로스·동시운영 상품 → 신규 스키마 (rocketGrowthItemData/marketplaceItemData)
// ─────────────────────────────────────────────────────────────

/** 신규 스키마 — 가격 데이터 */
export interface CoupangPriceData {
  originalPrice: number; // 할인율기준가 (정가)
  salePrice: number;     // 판매가격
}

/** 신규 스키마 — 채널별 아이템 데이터 (rocketGrowthItemData / marketplaceItemData 공통 골격) */
export interface CoupangChannelItemData {
  sellerProductItemId: number;
  isAutoGenerated?: boolean;
  vendorItemId: number | null; // 임시저장 상태면 null
  externalVendorSku?: string;
  barcode?: string;
  emptyBarcode?: boolean;
  modelNo?: string;
  maximumBuyCount?: number; // marketplaceItemData에만 존재
  priceData: CoupangPriceData;
  skuInfo?: Record<string, unknown>; // rocketGrowthItemData에만 존재
}

/** 기존 스키마 아이템 — 판매자배송 전용 상품 (가격이 평면 필드) */
export interface CoupangLegacyDetailItem {
  itemName: string;
  originalPrice: number;
  salePrice: number;
  vendorItemId: number | null;
  maximumBuyCount?: number;
  externalVendorSku?: string;
  [key: string]: unknown;
}

/** 신규 스키마 아이템 — 로켓그로스·동시운영 상품 */
export interface CoupangDualDetailItem {
  itemName: string;
  rocketGrowthItemData: CoupangChannelItemData | null; // 로켓그로스 미운영이면 null
  marketplaceItemData: CoupangChannelItemData | null;  // 로켓그로스 전용이면 null
  [key: string]: unknown;
}

/** 상품 단건 조회 응답 (스키마 판별 전 raw) */
export interface CoupangSellerProductDetailResponse {
  code: string;
  message: string;
  data: {
    sellerProductId: number;
    statusName: string;
    sellerProductName: string;
    displayProductName?: string;
    vendorId: string;
    brand?: string;
    saleStartedAt?: string;
    saleEndedAt?: string;
    items: Array<CoupangLegacyDetailItem | CoupangDualDetailItem>;
    rocketGrowthAdditionalInformation?: Record<string, unknown> | null;
    [key: string]: unknown;
  };
}

/** 스키마 종류 — 응답 자체가 판매방식의 물적 증거 */
export type CoupangProductSchemaType = "legacy" | "rocketGrowth";

/** 판매 채널 */
export type CoupangSaleChannel = "MARKETPLACE" | "ROCKET_GROWTH";

/** 정규화된 상품 옵션 — 스키마와 무관하게 동일 구조 */
export interface NormalizedProductOption {
  itemName: string;
  channel: CoupangSaleChannel;
  vendorItemId: number | null;
  originalPrice: number | null;
  salePrice: number | null;
  externalVendorSku?: string;
}

/** 정규화된 상품 — 이중 스키마 파싱 결과 */
export interface NormalizedSellerProduct {
  schemaType: CoupangProductSchemaType;
  sellerProductId: number;
  sellerProductName: string;
  statusName: string;
  vendorId: string;
  options: NormalizedProductOption[];
}

/** 정산 한 건 */
export interface CoupangSettlement {
  settlementId: number;
  orderId: number;
  orderItemId: number;
  orderTime: string;
  paymentTime: string;
  settledAt: string;
  sellerProductName: string;
  vendorItemName: string;
  quantity: number;
  unitPrice: number;
  shippingPrice: number;
  commission: number;
  settlementPrice: number;
}

/** 정산 목록 API 응답 */
export interface CoupangSettlementsResponse {
  code: string;
  message: string;
  data: CoupangSettlement[];
  nextToken?: string;
}
